### ISSUE TITLE
How to use it? 😅

### ISSUE THREAD

**Issue by StefMa** [Brightspace/ksiren#4]
Maybe a little bit dump question.
But.. how do I have to use that lib? 😃

I simple want to build Objects based on the json..How can I do that?

**Comment by MPomeroy** [comment]
Hi StefMa,

First off, thanks for the PR, very much appreciated! 

The basic purpose of KSiren is to provide an easy way to use responses you receive from a Siren API as classes in Kotlin by defining restrictions for the response. KSiren provides two levels of abstraction for this, the Entity level and the DefinedEntity level. DefinedEntities allow you specify required classes, actions, properties and links, so you can guarantee you're working with all the data you expect to have. At the entity level, the only restriction is that the json you provide conforms to the Siren spec.

If all you want is to build Entity objects out of json and don't want the additional validation of a DefinedEntity then you just need to call `Entity.fromJson(yourResponseReader)`.

There are more detailed steps for using the library in the wiki of this repo; if anything in there is ambiguous, let me know and I'll try and clarify it for you!
